### ISSUE TITLE
Error when rebuilding node-usb with electron

### ISSUE THREAD

**Issue by younesherlock** [tessel/node-usb#148]
I am building an app using Electron and node-usb, when I run the command 
**`.\node_modules\.bin\electron-rebuild.cmd`**
Here's what I get : 
```
node-pre-gyp ERR! node -v v6.9.1
node-pre-gyp ERR! node-pre-gyp -v v0.6.30
node-pre-gyp ERR! not ok

npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\TONPC\\Documents
\\electron\\electron-quick-start\\node_modules\\npm\\bin\\npm-cli.js" "rebuild"
"--runtime=electron" "--target=1.4.5" "--arch=x64" "--update-binary"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.9
npm ERR! code ELIFECYCLE
npm ERR! usb@1.2.0 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the usb@1.2.0 install script 'node-pre-gyp install --fallback
-to-build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the usb package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs usb
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls usb
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\TONPC\Documents\electron\electron-quick-start\node_modules
\npm-debug.log

Process exited with code: 1
Error: Process exited with code: 1
    at ChildProcess.<anonymous> (C:\Users\TONPC\Documents\electron\electron-quic
k-start\node_modules\electron-rebuild\lib\spawn.js:55:26)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
```
I am on Windows 8.1, Electron 1.4.5, Node 6.9.1, and usb 1.2.0

Any thoughts ?

**Comment by kevinmehall** [comment]
Closing all old Electron build related issues now that we have prebuilds for Electron in 1.6.0.
