### ISSUE TITLE
return process.dlopen(module,path._makeLong(filename))

### ISSUE THREAD

**Issue by heuuLZP** [tessel/node-usb#170]
I solved the question of  "node-pre-gyp install –fallback-to-build" , and finally show the message      
"node-pre-gyp info ok", but when I start node server ,there are som error........

Error: dlopen(/Users/callback/Documents/TM/server/node_modules/usb/src/binding/usb_bindings.node, 1): no suitable image found.  Did find:
	/Users/callback/Documents/TM/server/node_modules/usb/src/binding/usb_bindings.node: truncated mach-o error: segment __TEXT extends to 131072 which is past end of file 41984
    at Error (native)
    at Object.Module._extensions..node (module.js:568:18)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/callback/Documents/TM/server/node_modules/usb/usb.js:5:38)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)

can you help me?

**Comment by heuuLZP** [comment]
Let me explain why this issue was closed.

The main question is "npm install  node-usb" pause after "node-pre-gyp install –fallback-to-build", I read the article of "http://www.zgljl2012.com/node-pre-gyp-install- fallback-to-build-yi-zhi-qia-zhao-2/"  , I according to his method to solve . 

And then  hava the error "dlopen() ...".

Now I find Why  "node-pre-gyp install –fallback-to-build" pause.It is because  My mac OSX have a low version gcc(4.0.2),and I replace the high version gcc(6.0.2)。It work will for me .
