### ISSUE TITLE
user "root" does not have permission to access the dev dir "/home/pi/scanner/node_modules/usb/.node-gyp/8.9.2"

### ISSUE THREAD

**Issue by chemax** [tessel/node-usb#210]
Hi. I tried to install noble, bleno and just usb.
OS: raspbian (debian 8.0)
hardware: raspberry pi 3 (arm x64)
I have error:
many-many strings like that:
```gyp WARN EACCES user "root" does not have permission to access the dev dir "/home/pi/scanner/node_modules/usb/.node-gyp/8.9.2"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/home/pi/scanner/node_modules/usb/.node-gyp"
gyp WARN EACCES user "root" does not have permission to access the dev dir "/home/pi/scanner/node_modules/usb/.node-gyp/8.9.2"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/home/pi/scanner/node_modules/usb/.node-gyp"
gyp WARN EACCES user "root" does not have permission to access the dev dir "/home/pi/scanner/node_modules/usb/.node-gyp/8.9.2"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/home/pi/scanner/node_modules/usb/.node-gyp"
```
and after that this:
```gyp ERR! build error 
gyp ERR! stack Error: You must run `node-gyp configure` first!
gyp ERR! stack     at ReadFileContext.<anonymous> (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:49:20)
gyp ERR! stack     at ReadFileContext.callback (/usr/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:78:16)
gyp ERR! stack     at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:420:13)
gyp ERR! System Linux 4.9.24-v7+
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/home/pi/scanner/node_modules/usb/src/binding/usb_bindings.node" "--module_name=usb_bindings" "--module_path=/home/pi/scanner/node_modules/usb/src/binding"
gyp ERR! cwd /home/pi/scanner/node_modules/usb
gyp ERR! node -v v8.9.2
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/home/pi/scanner/node_modules/usb/src/binding/usb_bindings.node --module_name=usb_bindings --module_path=/home/pi/scanner/node_modules/usb/src/binding' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/home/pi/scanner/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:126:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:925:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
node-pre-gyp ERR! System Linux 4.9.24-v7+
node-pre-gyp ERR! command "/usr/bin/node" "/home/pi/scanner/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /home/pi/scanner/node_modules/usb
node-pre-gyp ERR! node -v v8.9.2
node-pre-gyp ERR! node-pre-gyp -v v0.6.39
node-pre-gyp ERR! not ok 
Failed to execute '/usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/home/pi/scanner/node_modules/usb/src/binding/usb_bindings.node --module_name=usb_bindings --module_path=/home/pi/scanner/node_modules/usb/src/binding' (1)
npm WARN bt-le-scanner@0.0.1 No description
npm WARN bt-le-scanner@0.0.1 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! usb@1.4.0 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the usb@1.4.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2017-12-06T11_02_33_071Z-debug.log
```

full log here. 
[2017-12-06T11_02_33_071Z-debug.log](https://github.com/tessel/node-usb/files/1535537/2017-12-06T11_02_33_071Z-debug.log)
Please, help me with this error!

**Comment by kevinmehall** [comment]
Don't run `npm` as root. Best way is to install node via `nvm`, which sets up permissions correctly to run `npm -g` as your normal user.

See https://github.com/nodejs/node-gyp/issues/454#issuecomment-315691803
