### ISSUE TITLE
I can't write binary data in usb flash drive

### ISSUE THREAD

**Issue by mahdi-gh1373** [tessel/node-usb#217]
I want to write some data  on my usb drive in linux.my code is like this : 
	
```

var usb = require('usb'),
    term = usb.findByIds(6518,24613);
term.open();
	var endpoints = term.interfaces[0].endpoints,
		inEndpoint = endpoints[0],
		outEndpoint = endpoints[1];
		//term.interfaces[0].claim()
	//inEndpoint.transferType = 2;
	//inEndpoint.startStream(1, 64);
	outEndpoint.transfer("ezdzdzxxxxcx", function (error, data) {
		if (!error) {
			console.log(data);
		} else {
			console.log(error);
		}
	});
	inEndpoint.on('data', function (data) {
		console.log(data);
	});
	inEndpoint.on('error', function (error) {
		console.log(error);
	});
```

but I have error:

```
{ Error: LIBUSB_ERROR_IO
    at OutEndpoint.transfer (/root/mytest/emptyproject/node_modules/usb/usb.js:380:45)
    at Controller.checkport (/root/mytest/emptyproject/controllers/api.js:332:13)
    at IncomingMessage.PROTO.$total_execute2 (/root/mytest/emptyproject/node_modules/total.js/index.js:13666:32)
    at IncomingMessage.PROTO.$total_execute (/root/mytest/emptyproject/node_modules/total.js/index.js:13636:9)
    at IncomingMessage.PROTO.$total_prepare (/root/mytest/emptyproject/node_modules/total.js/index.js:13934:9)
    at IncomingMessage.PROTO.$total_end2 (/root/mytest/emptyproject/node_modules/total.js/index.js:13780:9)
    at IncomingMessage.subscribe_end (/root/mytest/emptyproject/node_modules/total.js/index.js:9157:7)
    at IncomingMessage.PROTO.$total_end (/root/mytest/emptyproject/node_modules/total.js/index.js:13577:18)
    at Framework.F.$requestcontinue (/root/mytest/emptyproject/node_modules/total.js/index.js:6832:9)
    at Server.F.listener (/root/mytest/emptyproject/node_modules/total.js/index.js:6687:5) errno: -1 }

```

**Comment by kevinmehall** [comment]
This library provides raw access to USB endpoints. Your USB flash drive implements the USB Mass Storage Class, and `"ezdzdzxxxxcx"` is not a valid MSC command. I'm not sure what you're trying to do with this; while you could theoretically implement MSC and a filesystem in JS, you would be much better off using the existing kernel drivers -- mount the drive and use the `fs` API to read and write files on it.
