### ISSUE TITLE
In Endpoint Error On Mac OS X When Trying to Read

### ISSUE THREAD

**Issue by UsersDoProgram** [tessel/node-usb#238]
I have written a program that interfaces with Node JS and my PS4 USB Controller on Mac OS X 10.13, the code successfully runs, finds the device, opens it and finds the in endpoint, but an error is raised when trying to read. I ran the code in sudo and root and it doesn't make a difference. The code is found here: [control.txt](https://github.com/tessel/node-usb/files/1834537/control.txt)
Here is the output, 
Device Found
Device Opened.
Found InPoint
Waiting for data...
{ Error: LIBUSB_ERROR_NOT_FOUND
    at InEndpoint.transfer (/Volumes/U/Hall,Robert/2017-2018/_Myself/NodeCode/NodeCode/ControllerManipulator/node_modules/usb/usb.js:315:45)
    at Object.<anonymous> (/Volumes/U/Hall,Robert/2017-2018/_Myself/NodeCode/NodeCode/ControllerManipulator/control.js:33:13)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Function.Module.runMain (module.js:701:10)
    at startup (bootstrap_node.js:190:16)
    at bootstrap_node.js:662:3 errno: -5 } undefined

Does anyone know how I could resolve this?

**Comment by UsersDoProgram** [comment]
Found this is  a repost of issue #30
