### ISSUE TITLE
LIBUSB_ERROR_IO on Raspian (Raspberry Pi Linux)

### ISSUE THREAD

**Issue by abovino** [tessel/node-usb#250]
Hi, I'm receiving the following error on Raspian for Raspberry Pi.  The exact same code works on Windows 10.  Also, I am able to connect and stream outputs from the same device using Python on my Raspberry Pi with no issues.

Can anyone offer any advice?

```
events.js:165
      throw er; // Unhandled 'error' event
      ^

Error: LIBUSB_ERROR_IO
    at startTransfer (/home/pi/dev-projects/node-security/node_modules/usb/usb.js:347:6)
    at Array.forEach (<anonymous>)
    at InEndpoint.startPoll (/home/pi/dev-projects/node-security/node_modules/usb/usb.js:354:21)
    at Object.<anonymous> (/home/pi/dev-projects/node-security/app.js:10:24)
    at Module._compile (module.js:649:30)
    at Object.Module._extensions..js (module.js:660:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:501:12)
    at Function.Module._load (module.js:493:3)
    at Function.Module.runMain (module.js:690:10)
Emitted 'error' event at:
    at startTransfer (/home/pi/dev-projects/node-security/node_modules/usb/usb.js:349:9)
    at Array.forEach (<anonymous>)
    [... lines matching original stack trace ...]
    at Function.Module.runMain (module.js:690:10)
```

Here's my code ...

```javascript
const usb = require('usb');

let device = usb.findByIds(3034, 10296);
device.open();
device.interfaces[0].endpoints[0].transferType = 0 // Only get outputs when changing transferType to 0

interface = device.interfaces[0];
interface.claim();

interface.endpoints[0].startPoll(3, 65); // < == This line causing the error

interface.endpoints[0].on('data', (data) => {
  console.log(data);
});

interface.endpoints[0].on('error', (error) => {
  console.log(error);
});
```

**Comment by kevinmehall** [comment]
You can't change the transferType like that. It comes from the endpoint descriptor, and changing it in JS doesn't change what the kernel and device are expecting the endpoint type to be. I would expect to get a `LIBUSB_ERROR_IO` when attempting to submit a transfer with the wrong endpoint type.
