### ISSUE TITLE
TypeError: Cannot redefine property: configDescriptor

### ISSUE THREAD

**Issue by bodymindarts** [tessel/node-usb#255]
I'm using a library that brings in this package as a dependency but I cannot require it since the code of this package errors while loading:

```
    TypeError: Cannot redefine property: configDescriptor
        at Function.defineProperty (<anonymous>)

      4 | var Jest = require("@glennsl/bs-jest/src/jest.js");
      5 | var HwAppBtc = require("@ledgerhq/hw-app-btc");
    > 6 | var HwTransportNodeHid = require("@ledgerhq/hw-transport-node-hid");
      7 |
      8 | var TransportHid = /* module */[];
      9 |

      at Object.<anonymous> (node_modules/usb/usb.js:47:8)
      at Object.<anonymous> (node_modules/@ledgerhq/hw-transport-node-hid/lib/listenDevices.js:19:12)
      at Object.<anonymous> (node_modules/@ledgerhq/hw-transport-node-hid/lib/TransportNodeHid.js:55:23)
      at Object.<anonymous> (__tests__/ffi/Ledger_test.bs.js:6:26)
```

The require fails during execution of [this](https://github.com/tessel/node-usb/blob/master/usb.js#L47-L51) code. Can someone help me figure out whats going on?

I'm on mac Os 10.13.6 using node 10.6.0

**Comment by bodymindarts** [comment]
Nevermind, I found that I was accidentally loading this dependency twice.
