### ISSUE TITLE
Help For Electron? while packaging app for ai32 system

### ISSUE THREAD

**Issue by wahabch** [tessel/node-usb#259]
It says 

****Error: L:\angular\nodejs\node.exe exited with code 1
Error output:
node-pre-gyp WARN Using request for node-pre-gyp https download
node-pre-gyp WARN Tried to download(404): https://github.com/tessel/node-usb/releases/download/1.3.2/usb_bindings-v1.3.2-electron-v2.0-win32-ia32.tar.gz
node-pre-gyp WARN Pre-built binaries not found for usb@1.3.2 and electron@2.0.2 (electron-v2.0 ABI, unknown) (falling back to source compile with node-gyp)
node-pre-gyp WARN Pre-built binaries not installable for usb@1.3.2 and electron@2.0.2 (electron-v2.0 ABI, unknown) (falling back to source compile with node-gyp)
node-pre-gyp WARN Hit error Connection closed while downloading tarball file
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (L:\angular\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:258:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:237:12)
gyp ERR! System Windows_NT 10.0.16299
gyp ERR! command "L:\\angular\\nodejs\\node.exe" "L:\\angular\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "build" "--fallback-to-build" "--module=L:\\Commercial\\rpos_node\\node_modules\\usb\\src\\binding\\usb_bindings.node" "--module_name=usb_bindings" "--module_path=L:\\Commercial\\rpos_node\\node_modules\\usb\\src\\binding" "--napi_version=3" "--node_abi_napi=napi"
gyp ERR! cwd L:\Commercial\rpos_node\node_modules\usb
gyp ERR! node -v v10.2.1
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'L:\angular\nodejs\node.exe L:\angular\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js build --fallback-to-build --module=L:\Commercial\rpos_node\node_modules\usb\src\binding\usb_bindings.node --module_name=usb_bindings --module_path=L:\Commercial\rpos_node\node_modules\usb\src\binding --napi_version=3 --node_abi_napi=napi' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (L:\Commercial\rpos_node\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:961:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:5)
node-pre-gyp ERR! System Windows_NT 10.0.16299
node-pre-gyp ERR! command "L:\\angular\\nodejs\\node.exe" "L:\\Commercial\\rpos_node\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd L:\Commercial\rpos_node\node_modules\usb
node-pre-gyp ERR! node -v v10.2.1
node-pre-gyp ERR! node-pre-gyp -v v0.10.3
node-pre-gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! usb@1.3.2 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the usb@1.3.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\rko\AppData\Roaming\npm-cache\_logs\2018-08-15T21_52_10_103Z-debug.log

    at ChildProcess.childProcess.once.code (L:\Commercial\rpos_node\node_modules\builder-util\src\util.ts:252:14)
    at Object.onceWrapper (events.js:273:13)
    at ChildProcess.emit (events.js:182:13)
    at maybeClose (internal/child_process.js:961:16)
    at Socket.stream.socket.on (internal/child_process.js:380:11)
    at Socket.emit (events.js:182:13)
    at Pipe._handle.close [as _onclose] (net.js:596:12)
From previous event:
    at rebuild (L:\Commercial\rpos_node\node_modules\electron-builder-lib\out\util\yarn.js:234:18)
    at L:\Commercial\rpos_node\node_modules\electron-builder-lib\src\util\yarn.ts:20:11
    at Generator.next (<anonymous>)
    at runCallback (timers.js:696:18)
    at tryOnImmediate (timers.js:667:5)
    at processImmediate (timers.js:649:5)
From previous event:
    at installOrRebuild (L:\Commercial\rpos_node\node_modules\electron-builder-lib\out\util\yarn.js:68:17)
    at L:\Commercial\rpos_node\node_modules\electron-builder-lib\src\packager.ts:451:13
    at Generator.next (<anonymous>)
From previous event:
    at Packager.installAppDependencies (L:\Commercial\rpos_node\node_modules\electron-builder-lib\src\packager.ts:415:70)
    at L:\Commercial\rpos_node\node_modules\electron-builder-lib\src\packager.ts:365:20
    at Generator.next (<anonymous>)
From previous event:
    at Packager.doBuild (L:\Commercial\rpos_node\node_modules\electron-builder-lib\src\packager.ts:341:39)
    at L:\Commercial\rpos_node\node_modules\electron-builder-lib\src\packager.ts:317:52
    at Generator.next (<anonymous>)
    at L:\Commercial\rpos_node\node_modules\graceful-fs\graceful-fs.js:99:16
    at L:\Commercial\rpos_node\node_modules\graceful-fs\graceful-fs.js:43:10
    at FSReqWrap.oncomplete (fs.js:169:20)
From previous event:
    at Packager._build (L:\Commercial\rpos_node\node_modules\electron-builder-lib\src\packager.ts:294:133)
    at L:\Commercial\rpos_node\node_modules\electron-builder-lib\src\packager.ts:290:23
    at Generator.next (<anonymous>)
    at runCallback (timers.js:696:18)
    at tryOnImmediate (timers.js:667:5)
    at processImmediate (timers.js:649:5)
From previous event:
    at Packager.build (L:\Commercial\rpos_node\node_modules\electron-builder-lib\src\packager.ts:248:14)
    at L:\Commercial\rpos_node\node_modules\electron-builder-lib\src\index.ts:51:40
    at Generator.next (<anonymous>)
From previous event:
    at build (L:\Commercial\rpos_node\node_modules\electron-builder-lib\out\index.js:220:17)
    at build (L:\Commercial\rpos_node\node_modules\electron-builder\src\builder.ts:234:10)
    at then (L:\Commercial\rpos_node\node_modules\electron-builder\src\cli\cli.ts:46:19)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! RizwanPOS@1.0.0 dist: `build`
npm ERR! Exit** status 1**

**Comment by kevinmehall** [comment]
The duplicate `falling back to source compile with node-gyp` lines looks like https://github.com/mapbox/node-pre-gyp/issues/391. There's a fix for that in a node-pre-gyp upgrade, or the workaround is `npm install --build-from-source=usb`, or whatever the electron equivalent of that is.
