### ISSUE TITLE
Error: LIBUSB_ERROR_IO

### ISSUE THREAD

**Issue by tayler0101** [tessel/node-usb#270]
hi everyone i got this error when i try to transfer data to the usb Error: LIBUSB_ERROR_IO
this is my code:
```
var usb = require('usb');
var device= usb.findByIds(1027, 24577);
device.open()
var endpoints = device.interfaces[0].endpoints;
console.log(endpoints);
    var inEndpoint = endpoints[0];
    var outEndpoint = endpoints[1];
    inEndpoint.transferType = 0;
    inEndpoint.startPoll(1, 64);
    inEndpoint.transfer(64, function (error, data) {
        if (!error) {
            console.log(data);
        } else {
            console.log(error);
        }
    });
    inEndpoint.on('data', function (data) {
        console.log(data);
    });
    inEndpoint.on('error', function (error) {
        console.log(error);
    });
```

error:
```
[ 0.010565] [000005c9] libusb: error [submit_control_transfer] submiturb failed error -1 errno=16
[ 0.010605] [000005c9] libusb: debug [disarm_timerfd] 
[ 0.010620] [000005c9] libusb: error [submit_control_transfer] submiturb failed error -1 errno=16
[ 0.010624] [000005c9] libusb: debug [disarm_timerfd] 
{ Error: LIBUSB_ERROR_IO
    at InEndpoint.transfer (/home/user/Documents/Projects/nodeJS/usb/node_modules/usb/usb.js:321:45)
    at Object.<anonymous> (/home/user/Documents/Projects/nodeJS/usb/usbLibrary.js:15:16)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3 errno: -1 }
```

**Comment by tayler0101** [comment]
sorry i forgot to call claim()
