### ISSUE TITLE
electron build error

### ISSUE THREAD

**Issue by fangjunai** [tessel/node-usb#283]
electron-vue:2.0.4
win7 ia32
-----------------------------------
Error output:
node-pre-gyp WARN Using request for node-pre-gyp https download
node-pre-gyp WARN Tried to download(404): https://github.com/tessel/node-usb/releases/download/1.3.2/usb_bindings-v1.3.2-electron-v2.0-win32-ia32.tar.gz
node-pre-gyp WARN Pre-built binaries not found for usb@1.3.2 and electron@2.0.13 (electron-v2.0 ABI, unknown) (falling back to source compile with node-gyp)
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\fubao\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:240:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\fubao\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "build" "--fallback-to-build" "--module=D:\\demo\\node_modules\\usb\\src\\binding\\usb_bindings.node" "--module_name=usb_bindings" "--module_path=D:\\demo\\node_modules\\usb\\src\\binding" "--napi_version=3" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=electron-v2.0"
gyp ERR! cwd D:\demo\node_modules\usb
gyp ERR! node -v v10.13.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'C:\Program Files\nodejs\node.exe C:\Users\fubao\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js build --fallback-to-build --module=D:\demo\node_modules\usb\src\binding\usb_bindings.node --module_name=usb_bindings --module_path=D:\demo\node_modules\usb\src\binding --napi_version=3 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=electron-v2.0' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (D:\demo\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:962:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
node-pre-gyp ERR! System Windows_NT 6.1.7601
node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "D:\\demo\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd D:\demo\node_modules\usb
node-pre-gyp ERR! node -v v10.13.0
node-pre-gyp ERR! node-pre-gyp -v v0.11.0
node-pre-gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! usb@1.3.2 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the usb@1.3.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\fubao\AppData\Roaming\npm-cache\_logs\2018-11-13T02_27_44_282Z-debug.log

    at ChildProcess.childProcess.once.code (D:\demo\node_modules\builder-util\src\util.ts:254:14)
    at Object.onceWrapper (events.js:273:13)
    at ChildProcess.emit (events.js:182:13)
    at maybeClose (internal/child_process.js:962:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
From previous event:
    at rebuild (D:\demo\node_modules\app-builder-lib\out\util\yarn.js:239:18)
    at D:\demo\node_modules\app-builder-lib\src\util\yarn.ts:20:11
    at Generator.next (<anonymous>)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
From previous event:
    at installOrRebuild (D:\demo\node_modules\app-builder-lib\out\util\yarn.js:68:17)
    at D:\demo\node_modules\app-builder-lib\src\packager.ts:457:13
    at Generator.next (<anonymous>)
From previous event:
    at Packager.installAppDependencies (D:\demo\node_modules\app-builder-lib\src\packager.ts:418:70)
    at D:\demo\node_modules\app-builder-lib\src\packager.ts:368:20
    at Generator.next (<anonymous>)
From previous event:
    at Packager.doBuild (D:\demo\node_modules\app-builder-lib\src\packager.ts:344:39)
    at D:\demo\node_modules\app-builder-lib\src\packager.ts:314:57
From previous event:
    at Packager._build (D:\demo\node_modules\app-builder-lib\src\packager.ts:285:133)
    at D:\demo\node_modules\app-builder-lib\src\packager.ts:281:23
    at Generator.next (<anonymous>)
From previous event:
    at Packager.build (D:\demo\node_modules\app-builder-lib\src\packager.ts:238:14)
    at build (D:\demo\node_modules\app-builder-lib\src\index.ts:58:28)
    at build (D:\demo\node_modules\electron-builder\src\builder.ts:227:10)
    at then (D:\demo\node_modules\electron-builder\src\cli\cli.ts:42:48)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
From previous event:
    at Object.args [as handler] (D:\demo\node_modules\electron-builder\src\cli\cli.ts:42:48)
    at Object.runCommand (D:\demo\node_modules\yargs\lib\command.js:238:44)
    at Object.parseArgs [as _parseArgs] (D:\demo\node_modules\yargs\yargs.js:1085:24)
    at Object.get [as argv] (D:\demo\node_modules\yargs\yargs.js:1000:21)
    at Object.<anonymous> (D:\demo\node_modules\electron-builder\src\cli\cli.ts:25:28)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:741:12)
    at startup (internal/bootstrap/node.js:285:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:739:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! demo@0.0.1 build: `node .electron-vue/build.js && electron-builder`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the demo@0.0.1 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\fubao\AppData\Roaming\npm-cache\_logs\2018-11-13T02_27_44_361Z-debug.log
-----------------------------------------
2018-11-13T02_27_44_361Z-debug.log :

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\fubao\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'build' ]
2 info using npm@6.4.1
3 info using node@v10.13.0
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle demo@0.0.1~prebuild: demo@0.0.1
6 info lifecycle demo@0.0.1~build: demo@0.0.1
7 verbose lifecycle demo@0.0.1~build: unsafe-perm in lifecycle true
8 verbose lifecycle demo@0.0.1~build: PATH: C:\Users\fubao\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;D:\demo\node_modules\.bin;C:\Users\fubao\bin;C:\Program Files\Git\mingw32\bin;C:\Program Files\Git\usr\local\bin;C:\Program Files\Git\usr\bin;C:\Program Files\Git\usr\bin;C:\Program Files\Git\mingw32\bin;C:\Program Files\Git\usr\bin;C:\Users\fubao\bin;C:\Python27;C:\Python27\Scripts;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0;C:\Program Files\Git\cmd;C:\Program Files\Microsoft SQL Server\100\Tools\Binn;C:\Program Files\Microsoft SQL Server\100\DTS\Binn;C:\Program Files\nodejs;C:\Users\fubao\AppData\Local\Programs\Microsoft VS Code\bin;C:\Users\fubao\AppData\Roaming\npm;C:\Program Files\Git\usr\bin\vendor_perl;C:\Program Files\Git\usr\bin\core_perl
9 verbose lifecycle demo@0.0.1~build: CWD: D:\demo
10 silly lifecycle demo@0.0.1~build: Args: [ '/d /s /c',
10 silly lifecycle   'node .electron-vue/build.js && electron-builder' ]
11 silly lifecycle demo@0.0.1~build: Returned: code: 1  signal: null
12 info lifecycle demo@0.0.1~build: Failed to exec build script
13 verbose stack Error: demo@0.0.1 build: `node .electron-vue/build.js && electron-builder`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Users\fubao\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:182:13)
13 verbose stack     at ChildProcess.<anonymous> (C:\Users\fubao\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:182:13)
13 verbose stack     at maybeClose (internal/child_process.js:962:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
14 verbose pkgid demo@0.0.1
15 verbose cwd D:\demo
16 verbose Windows_NT 6.1.7601
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\fubao\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
18 verbose node v10.13.0
19 verbose npm  v6.4.1
20 error code ELIFECYCLE
21 error errno 1
22 error demo@0.0.1 build: `node .electron-vue/build.js && electron-builder`
22 error Exit status 1
23 error Failed at the demo@0.0.1 build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by fangjunai** [comment]
need  windows-build-tools 2015   thanks  node-usb
