### ISSUE TITLE
Cannot open 

### ISSUE THREAD

**Issue by buuuudzik** [tessel/node-usb#286]

**Comment by buuuudzik** [comment]
I have above error on Windows 7 64-bit when I try .open a device.
I've tried with pendrive, printer and also some key stick.

`const usb = require('usb');

const deviceList = usb.getDeviceList(); // Lists all usb ports
console.table(deviceList);

const device = usb.findByIds(0x04f9, 0x02df); // vid: 04F2, pid: B217
const {iManufacturer} = device.deviceDescriptor;
console.log(device, iManufacturer); // Founded device

device.open();
device.getStringDescriptor(iManufacturer, (err, man) => {
    console.log(man);
    device.close();
});
`

Below full error:
Error: LIBUSB_ERROR_NOT_FOUND
    at Device.usb.Device.open (D:\Projekty\Freelancer.com\Ser
    at Object.<anonymous> (D:\Projekty\Freelancer.com\Serialp
    at Module._compile (internal/modules/cjs/loader.js:688:30
    at Object.Module._extensions..js (internal/modules/cjs/lo
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:
    at Function.Module.runMain (internal/modules/cjs/loader.j
    at startup (internal/bootstrap/node.js:285:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:739:3)

**Comment by buuuudzik** [comment]
This was because I've hadn't installed the generic driver via Zadig which is mention in the first lines in this library description;)
