### ISSUE TITLE
Can't build with Node 12 on Mac OS X

### ISSUE THREAD

**Issue by ynaut** [tessel/node-usb#337]
**Version**: 1.6.0
**Node Version** : 12.4.0
**OS**: Darwin 18.6.0

``` $ prebuild-install --verbose || node-gyp rebuild
      CC(target) Release/obj.target/libusb/libusb/libusb/core.o
      CC(target) Release/obj.target/libusb/libusb/libusb/descriptor.o
      CC(target) Release/obj.target/libusb/libusb/libusb/hotplug.o
      CC(target) Release/obj.target/libusb/libusb/libusb/io.o
      CC(target) Release/obj.target/libusb/libusb/libusb/strerror.o
      CC(target) Release/obj.target/libusb/libusb/libusb/sync.o
      CC(target) Release/obj.target/libusb/libusb/libusb/os/poll_posix.o
      CC(target) Release/obj.target/libusb/libusb/libusb/os/threads_posix.o
      CC(target) Release/obj.target/libusb/libusb/libusb/os/darwin_usb.o
      LIBTOOL-STATIC Release/usb.a
      CXX(target) Release/obj.target/usb_bindings/src/node_usb.o
    info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

                    errorOut=prebuild-install info begin Prebuild-install version 5.3.3
    prebuild-install info looking for cached prebuild @ /Users/smrt/.npm/_prebuilds/c39fd4-usb-v1.6.0-electron-v75-darwin-x64.tar.gz
    prebuild-install http request GET https://github.com/tessel/node-usb/releases/download/v1.6.0/usb-v1.6.0-electron-v75-darwin-x64.tar.gz
    prebuild-install http 404 https://github.com/tessel/node-usb/releases/download/v1.6.0/usb-v1.6.0-electron-v75-darwin-x64.tar.gz
    prebuild-install WARN install No prebuilt binaries found (target=7.1.0 runtime=electron arch=x64 libc= platform=darwin)
    gyp info it worked if it ends with ok
    gyp info using node-gyp@3.8.0
    gyp info using node@12.4.0 | darwin | x64
    gyp info spawn /usr/bin/python
    gyp info spawn args [
    gyp info spawn args   '/Users/smrt/.nvm/versions/node/v12.4.0/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
    gyp info spawn args   'binding.gyp',
    gyp info spawn args   '-f',
    gyp info spawn args   'make',
    gyp info spawn args   '-I',
    gyp info spawn args   '/Users/smrt/projects/smrt-system/electron/node_modules/usb/build/config.gypi',
    gyp info spawn args   '-I',
    gyp info spawn args   '/Users/smrt/.nvm/versions/node/v12.4.0/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
    gyp info spawn args   '-I',
    gyp info spawn args   '/Users/smrt/.electron-gyp/7.1.0/include/node/common.gypi',
    gyp info spawn args   '-Dlibrary=shared_library',
    gyp info spawn args   '-Dvisibility=default',
    gyp info spawn args   '-Dnode_root_dir=/Users/smrt/.electron-gyp/7.1.0',
    gyp info spawn args   '-Dnode_gyp_dir=/Users/smrt/.nvm/versions/node/v12.4.0/lib/node_modules/npm/node_modules/node-gyp',
    gyp info spawn args   '-Dnode_lib_file=/Users/smrt/.electron-gyp/7.1.0/<(target_arch)/node.lib',
    gyp info spawn args   '-Dmodule_root_dir=/Users/smrt/projects/smrt-system/electron/node_modules/usb',
    gyp info spawn args   '-Dnode_engine=v8',
    gyp info spawn args   '--depth=.',
    gyp info spawn args   '--no-parallel',
    gyp info spawn args   '--generator-output',
    gyp info spawn args   'build',
    gyp info spawn args   '-Goutput_dir=.'
    gyp info spawn args ]
    gyp info spawn make
    gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
    ../libusb/libusb/core.c:2241:35: warning: comparison of integers of different signs: 'int' and 'unsigned long' [-Wsign-compare]
            if (header_len < 0 || header_len >= sizeof(buf)) {
                                  ~~~~~~~~~~ ^  ~~~~~~~~~~~
    ../libusb/libusb/core.c:2250:44: warning: comparison of integers of different signs: 'int' and 'unsigned long' [-Wsign-compare]
            if (text_len < 0 || text_len + header_len >= sizeof(buf)) {
                                ~~~~~~~~~~~~~~~~~~~~~ ^  ~~~~~~~~~~~
    2 warnings generated.
    ../libusb/libusb/os/darwin_usb.c:344:3: warning: 'objc_registerThreadWithCollector' is deprecated: it does nothing. Define OBJC_SILENCE_GC_DEPRECATIONS=1 to temporarily silence this diagnostic. [-Wdeprecated-declarations]
      objc_registerThreadWithCollector();
      ^
    /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/objc/objc-auto.h:243:1: note: 'objc_registerThreadWithCollector' has been explicitly marked deprecated here
    OBJC_GC_DEPRECATED("it does nothing")
    ^
    /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/objc/objc-auto.h:45:55: note: expanded from macro 'OBJC_GC_DEPRECATED'
    #   define OBJC_GC_DEPRECATED(message) __attribute__((deprecated(message ". Define OBJC_SILENCE_GC_DEPRECATIONS=1 to temporarily silence this diagnostic.")))
                                                          ^
    ../libusb/libusb/os/darwin_usb.c:1281:27: warning: expression which evaluates to zero treated as a null pointer constant of type 'IOUSBInterfaceInterface550 **' (aka 'struct IOUSBInterfaceStruct550 **') [-Wnon-literal-null-conversion]
      cInterface->interface = IO_OBJECT_NULL;
                              ^~~~~~~~~~~~~~
    /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/IOKit.framework/Headers/IOTypes.h:161:25: note: expanded from macro 'IO_OBJECT_NULL'
    #define IO_OBJECT_NULL  ((io_object_t) 0)
                            ^~~~~~~~~~~~~~~~~
    2 warnings generated.
    ../src/node_usb.cc:66:10: error: no matching member function for call to 'Set'
            target->Set(Nan::New<String>("INIT_ERROR").ToLocalChecked(), Nan::New<Number>(res));
            ~~~~~~~~^~~
    /Users/smrt/.electron-gyp/7.1.0/include/node/v8.h:3455:37: note: candidate function not viable: requires 3 arguments, but 2 were provided
      V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
                                        ^
    /Users/smrt/.electron-gyp/7.1.0/include/node/v8.h:3458:37: note: candidate function not viable: requires 3 arguments, but 2 were provided
      V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
                                        ^
    ../src/node_usb.cc:116:8: error: no matching member function for call to 'Set'
                    arr->Set(i, Device::get(devs[i]));
                    ~~~~~^~~
    /Users/smrt/.electron-gyp/7.1.0/include/node/v8.h:3455:37: note: candidate function not viable: requires 3 arguments, but 2 were provided
      V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
                                        ^
    /Users/smrt/.electron-gyp/7.1.0/include/node/v8.h:3458:37: note: candidate function not viable: requires 3 arguments, but 2 were provided
      V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
                                        ^
    ../src/node_usb.cc:151:7: warning: 'MakeCallback' is deprecated [-Wdeprecated-declarations]
            Nan::MakeCallback(Nan::New(hotplugThis), "emit", 2, argv);
                 ^
    ../node_modules/nan/nan.h:1001:3: note: 'MakeCallback' has been explicitly marked deprecated here
      NAN_DEPRECATED inline v8::Local<v8::Value> MakeCallback(
      ^
    ../node_modules/nan/nan.h:103:40: note: expanded from macro 'NAN_DEPRECATED'
    # define NAN_DEPRECATED __attribute__((deprecated))
                                           ^
    ../src/node_usb.cc:301:22: error: no matching member function for call to 'Set'
            e.As<v8::Object>()->Set(Nan::New<String>("errno").ToLocalChecked(), Nan::New<Integer>(errorno));
            ~~~~~~~~~~~~~~~~~~~~^~~
    /Users/smrt/.electron-gyp/7.1.0/include/node/v8.h:3455:37: note: candidate function not viable: requires 3 arguments, but 2 were provided
      V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
                                        ^
    /Users/smrt/.electron-gyp/7.1.0/include/node/v8.h:3458:37: note: candidate function not viable: requires 3 arguments, but 2 were provided
      V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
                                        ^
    1 warning and 3 errors generated.
    make: *** [Release/obj.target/usb_bindings/src/node_usb.o] Error 1
    gyp ERR! build error
    gyp ERR! stack Error: `make` failed with exit code: 2
    gyp ERR! stack     at ChildProcess.onExit (/Users/smrt/.nvm/versions/node/v12.4.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
    gyp ERR! stack     at ChildProcess.emit (events.js:200:13)
    gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
    gyp ERR! System Darwin 18.6.0
    gyp ERR! command "/Users/smrt/.nvm/versions/node/v12.4.0/bin/node" "/Users/smrt/.nvm/versions/node/v12.4.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
    gyp ERR! cwd /Users/smrt/projects/smrt-system/electron/node_modules/usb
    gyp ERR! node -v v12.4.0
    gyp ERR! node-gyp -v v3.8.0
    gyp ERR! not ok
    error Command failed with exit code 1.```

**Comment by kevinmehall** [comment]
Fixed in #338
