### ISSUE TITLE
no suitable image found  &&  unknown file type

### ISSUE THREAD

**Issue by saifeiLee** [tessel/node-usb#360]
Hello, I have a question:
```bash
App threw an error during load
Error: dlopen(/Users/waltermitty/Code/cvte/electron-easi-camera/app/node_modules/usb/build/Release/usb_bindings.node, 1): no suitable image found.  Did find:
	/Users/waltermitty/Code/cvte/electron-easi-camera/app/node_modules/usb/build/Release/usb_bindings.node: unknown file type, first eight bytes: 0x4D 0x5A 0x90 0x00 0x03 0x00 0x00 0x00
	/Users/waltermitty/Code/cvte/electron-easi-camera/app/node_modules/usb/build/Release/usb_bindings.node: unknown file type, first eight bytes: 0x4D 0x5A 0x90 0x00 0x03 0x00 0x00 0x00
    at process.func (electron/js2c/asar.js:140:31)
    at process.func [as dlopen] (electron/js2c/asar.js:140:31)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1016:18)
    at Object.func (electron/js2c/asar.js:140:31)
    at Object.func [as .node] (electron/js2c/asar.js:140:31)
    at Module.load (internal/modules/cjs/loader.js:816:32)
    at Module._load (internal/modules/cjs/loader.js:728:14)
    at Module._load (electron/js2c/asar.js:717:26)
    at Function.Module._load (electron/js2c/asar.js:717:26)
    at Module.require (internal/modules/cjs/loader.js:853:19)
```
Electron version: 8.1.0
node-usb:^1.6.3

Reinstall node-usb can fix this issue temporarily, I wanna know why this error occur and how can i fix it permanently?

If you need any further info ,please let me know. Thanks a lot~

**Comment by kevinmehall** [comment]
0x4d 0x5a looks like the beginning of a Windows dll, while the `/Users/` paths look like macOS. Make sure you're installing the right version of the `.node` file for your OS.
