### ISSUE TITLE
TypeError: Cannot read property 'indexOf' of undefined when start app

### ISSUE THREAD

**Issue by liuzhenyilang** [tessel/node-usb#372]
`[1] [14:00:15.052] [error] TypeError: Cannot read property 'indexOf' of undefined
[1]     at Function.getFileName (webpack:///./node_modules/bindings/bindings.js?:178:16)
[1]     at bindings (webpack:///./node_modules/bindings/bindings.js?:82:48)
[1]     at eval (webpack:///./node_modules/usb/usb.js?:1:112)
[1]     at Object../node_modules/usb/usb.js (G:\project\LLL\boom-meet-electron\build\main.js:2828:1)
[1]     at __webpack_require__ (G:\project\LLL\boom-meet-electron\build\main.js:20:30)
[1]     at createBoomMeetWindow (webpack:///./main.js?:1575:17)
[1]     at App.eval (webpack:///./main.js?:2431:5)
[1]     at App.emit (events.js:215:7)`

**Comment by kevinmehall** [comment]
node-usb is not compatible with webpack.
