### ISSUE TITLE
Re-import failures in jest

### ISSUE THREAD

**Issue by ppershing** [tessel/node-usb#412]
When we run multiple of our test files in jest (together with --runInBand to serialize the execution), we are getting weird errors in `node-usb` in all but first testfile:
```
  ● Test suite failed to run

    TypeError: Cannot redefine property: configDescriptor
        at Function.defineProperty (<anonymous>)

      at Object.<anonymous> (node_modules/usb/usb.js:52:8)
      at Object.<anonymous> (node_modules/@ledgerhq/hw-transport-node-hid/src/listenDevices.js:6:1)
```
I am not sure about how exactly Jest manages to re-import the file (it might be some fun with es6 imports vs commonjs require as `hw-transport-node-hid` is using es6 imports) but the library obviously doesn't like it.
Looking at details, it tries twice to modify `bindings` package as we have `var usb = exports = module.exports = require('bindings')('usb_bindings');` and then crashes at `Object.defineProperty(usb.Device.prototype, "configDescriptor", {`

Would it be possible to make implementation resilient and bail out if usb.Device.prototype was already modified?

**Comment by notaphplover** [comment]
This is so frustrating, there seems to be no easy workaround for this and two years have passed. Has anyone found a way to workaround this?
