### ISSUE TITLE
LIBUSB_ERROR_IO on Ubuntu

### ISSUE THREAD

**Issue by dvil88** [tessel/node-usb#414]
Well I'm experiencing some issues in Ubuntu 20.04 (couldn't test in any other version). This is the test code:

```
const usb = require('usb')
usb.setDebugLevel(4)


const bitmask = (int) => int.toString(2).split('').reverse().map(i => parseInt(i))

var device = usb.getDeviceList().filter((device) => {
	return device.deviceDescriptor.idVendor === 11902 && device.deviceDescriptor.idProduct === 2093;
})[0];

device.open();

// auto_exposure_mode
var params = { wValue: 512, wIndex: 768, wLength: 1 };

// BM_REQUEST_TYPE.GET = 161
// REQUEST.GET_INFO = 134

device.controlTransfer(161, 134, params.wValue, params.wIndex, params.wLength, (error, buffer) => {
	if( error ){
		return console.error(error);
	}

	const bm = bitmask(buffer.readIntLE(0, buffer.byteLength))
	const info = {
		// D0 Supports GET value requests Capability
		get: Boolean(bm[0]),
		// D1 Supports SET value requests Capability
		set: Boolean(bm[1]),
		// D2 Disabled due to automatic mode (under device control) State
		disabled: Boolean(bm[2]),
		// D3 Autoupdate Control (see section 2.4.2.2 "Status Interrupt Endpoint")
		autoUpdate: Boolean(bm[3]),
		// D4 Asynchronous Control (see sections 2.4.2.2 "Status Interrupt Endpoint" and 2.4.4, “Control Transfer and Request Processing”)
		async: Boolean(bm[3]),
	}
	console.log(info);
});
```

And these are the results in Ubuntu 20.04,  MacOS 10.15 and Windows 10:

**Ubuntu 20.04**

> Node version: v14.16.0
> NPM version: 6.14.11
> node_usb version: 1.6.5
> libusb version: 2:1.0.23-2build1

Result:
```
[timestamp] [threadID] facility level [function call] <message>
--------------------------------------------------------------------------------
[ 0.005539] [00009570] libusb: debug [libusb_get_device_list] 
[ 0.005555] [00009570] libusb: debug [discovered_devs_append] need to increase capacity
[ 0.005557] [00009570] libusb: debug [discovered_devs_append] need to increase capacity
[ 0.005579] [00009570] libusb: debug [libusb_get_device_descriptor] 
[ 0.005612] [00009570] libusb: debug [libusb_get_device_descriptor] 
[ 0.005630] [00009570] libusb: debug [libusb_get_device_descriptor] 
[ 0.005647] [00009570] libusb: debug [libusb_get_device_descriptor] 
[ 0.005663] [00009570] libusb: debug [libusb_get_device_descriptor] 
[ 0.005679] [00009570] libusb: debug [libusb_get_device_descriptor] 
[ 0.005696] [00009570] libusb: debug [libusb_get_device_descriptor] 
[ 0.005712] [00009570] libusb: debug [libusb_get_device_descriptor] 
[ 0.005729] [00009570] libusb: debug [libusb_get_device_descriptor] 
[ 0.005745] [00009570] libusb: debug [libusb_get_device_descriptor] 
[ 0.005762] [00009570] libusb: debug [libusb_get_device_descriptor] 
[ 0.005779] [00009570] libusb: debug [libusb_get_device_descriptor] 
[ 0.005796] [00009570] libusb: debug [libusb_get_device_descriptor] 
[ 0.005813] [00009570] libusb: debug [libusb_get_device_descriptor] 
[ 0.005830] [00009570] libusb: debug [libusb_get_device_descriptor] 
[ 0.005846] [00009570] libusb: debug [libusb_get_device_descriptor] 
[ 0.005863] [00009570] libusb: debug [libusb_get_device_descriptor] 
[ 0.005917] [00009570] libusb: debug [libusb_open] open 1.11
[ 0.122345] [00009570] libusb: debug [usbi_add_pollfd] add fd 25 events 4
[ 0.122375] [00009578] libusb: debug [handle_events] poll() returned 1
[ 0.122385] [00009578] libusb: debug [handle_events] caught a fish on the control pipe
[ 0.122391] [00009578] libusb: debug [libusb_try_lock_events] someone else is modifying poll fds
[ 0.122395] [00009578] libusb: debug [libusb_event_handler_active] someone else is modifying poll fds
[ 0.122398] [00009578] libusb: debug [libusb_handle_events_timeout_completed] another thread is doing event handling
[ 0.122411] [00009578] libusb: debug [libusb_handle_events_timeout_completed] doing our own event handling
[ 0.122413] [00009578] libusb: debug [handle_events] poll fds modified, reallocating
[ 0.122416] [00009578] libusb: debug [handle_events] poll() 4 fds with timeout in 60000ms
[ 0.122513] [00009570] libusb: debug [parse_configuration] skipping descriptor 0xb

[ 0.122524] [00009570] libusb: debug [parse_endpoint] skipping descriptor 25
[ 0.123107] [00009570] libusb: debug [add_to_flying_list] arm timerfd for timeout in 1000ms (first in line)
[ 0.123121] [00009570] libusb: error [submit_control_transfer] submiturb failed error -1 errno=16
[ 0.123123] [00009570] libusb: debug [disarm_timerfd] 
[ 0.123125] [00009570] libusb: debug [add_to_flying_list] arm timerfd for timeout in 1000ms (first in line)
[ 0.123128] [00009570] libusb: error [submit_control_transfer] submiturb failed error -1 errno=16
[ 0.123131] [00009570] libusb: debug [disarm_timerfd] 
Error: LIBUSB_ERROR_IO
    at Device.usb.Device.controlTransfer (/tmp/testCams/node_modules/usb/usb.js:140:12)
    at Object.<anonymous> (/tmp/testCams/testDevice.js:18:8)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47 {
  errno: -1
}
```

**MacOS 10.15**

> Node version: v14.16.0
> NPM version: 6.14.11
> node_usb version: 1.6.5

Result:
```
[timestamp] [threadID] facility level [function call] <message>
--------------------------------------------------------------------------------
[ 0.010512] [00000307] libusb: debug [libusb_get_device_list] 
[ 0.011334] [00000307] libusb: debug [libusb_get_device_descriptor] 
[ 0.011543] [00000307] libusb: debug [libusb_get_device_descriptor] 
[ 0.011582] [00000307] libusb: debug [libusb_get_device_descriptor] 
[ 0.011611] [00000307] libusb: debug [libusb_get_device_descriptor] 
[ 0.011642] [00000307] libusb: debug [libusb_get_device_descriptor] 
[ 0.011668] [00000307] libusb: debug [libusb_get_device_descriptor] 
[ 0.011693] [00000307] libusb: debug [libusb_get_device_descriptor] 
[ 0.011851] [00000307] libusb: debug [libusb_open] open 20.7
[ 0.012009] [00000307] libusb: debug [usbi_add_pollfd] add fd 24 events 1
[ 0.012017] [00000307] libusb: debug [darwin_open] device open for access
[ 0.012058] [00003913] libusb: debug [handle_events] poll() returned 1
[ 0.012070] [00003913] libusb: debug [handle_events] caught a fish on the control pipe
[ 0.012101] [00003913] libusb: debug [libusb_get_next_timeout] no URBs, no timeout!
[ 0.012108] [00003913] libusb: debug [libusb_try_lock_events] someone else is modifying poll fds
[ 0.012113] [00003913] libusb: debug [libusb_event_handler_active] someone else is modifying poll fds
[ 0.012118] [00003913] libusb: debug [libusb_handle_events_timeout_completed] another thread is doing event handling
[ 0.012215] [00003913] libusb: debug [libusb_get_next_timeout] no URBs, no timeout!
[ 0.012224] [00003913] libusb: debug [libusb_handle_events_timeout_completed] doing our own event handling
[ 0.012229] [00003913] libusb: debug [handle_events] poll fds modified, reallocating
[ 0.012236] [00003913] libusb: debug [handle_events] poll() 3 fds with timeout in 60000ms
[ 0.012352] [00000307] libusb: debug [parse_configuration] skipping descriptor 0xb

[ 0.012382] [00000307] libusb: debug [parse_endpoint] skipping descriptor 25
[ 0.014609] [00004f07] libusb: debug [darwin_async_io_callback] an async io operation has completed
[ 0.014654] [00003913] libusb: debug [handle_events] poll() returned 1
[ 0.014666] [00003913] libusb: debug [op_handle_events] checking fd 24 with revents = 1
[ 0.014674] [00003913] libusb: debug [darwin_handle_callback] handling control completion with kernel status 0
[ 0.014681] [00003913] libusb: debug [usbi_handle_transfer_completion] transfer 0x104c5f558 has callback 0x104f5b0b0
[ 0.014707] [00003913] libusb: debug [libusb_get_next_timeout] no URBs, no timeout!
[ 0.014714] [00003913] libusb: debug [libusb_handle_events_timeout_completed] doing our own event handling
[ 0.014719] [00003913] libusb: debug [handle_events] poll() 3 fds with timeout in 60000ms
{
  get: true,
  set: true,
  disabled: false,
  autoUpdate: false,
  async: false
}
```

**Windows 10**

> Node version: v14.16.0
> NPM version: 6.14.11
> node_usb version: 1.6.5

Result:
```
[timestamp] [threadID] facility level [function call] <message>
--------------------------------------------------------------------------------
[ 0.079149] [000001c8] libusb: debug [libusb_get_device_list]
[ 0.082146] [000001c8] libusb: debug [discovered_devs_append] need to increase capacity
[ 0.082146] [000001c8] libusb: debug [libusb_get_device_descriptor]
[ 0.083145] [000001c8] libusb: debug [libusb_get_device_descriptor]
[ 0.083145] [000001c8] libusb: debug [libusb_get_device_descriptor]
[ 0.084146] [000001c8] libusb: debug [libusb_get_device_descriptor]
[ 0.085146] [000001c8] libusb: debug [libusb_get_device_descriptor]
[ 0.085933] [000001c8] libusb: debug [libusb_get_device_descriptor]
[ 0.085933] [000001c8] libusb: debug [libusb_get_device_descriptor]
[ 0.086947] [000001c8] libusb: debug [libusb_get_device_descriptor]
[ 0.086947] [000001c8] libusb: debug [libusb_get_device_descriptor]
[ 0.087937] [000001c8] libusb: debug [libusb_get_device_descriptor]
[ 0.087937] [000001c8] libusb: debug [libusb_get_device_descriptor]
[ 0.088936] [000001c8] libusb: debug [libusb_get_device_descriptor]
[ 0.091087] [000001c8] libusb: debug [libusb_open] open 2.2
[ 0.092082] [000001c8] libusb: debug [parse_configuration] skipping descriptor 0xb

[ 0.092082] [000001c8] libusb: debug [parse_endpoint] skipping descriptor 25
[ 0.095087] [000001c8] libusb: debug [composite_submit_control_transfer] using interface 0
[ 0.095087] [000001c8] libusb: debug [libusb_claim_interface] interface 0
[ 0.095087] [000001c8] libusb: debug [winusbx_claim_interface] claimed interface 0
[ 0.096087] [000001c8] libusb: debug [libusb_get_config_descriptor] index 0
[ 0.096848] [000001c8] libusb: debug [parse_configuration] skipping descriptor 0xb

[ 0.096848] [000001c8] libusb: debug [parse_endpoint] skipping descriptor 25
[ 0.096848] [000001c8] libusb: debug [windows_assign_endpoints] no endpoints found for interface 0
[ 0.097850] [000001c8] libusb: debug [auto_claim] auto-claimed interface 0 for control request
[ 0.097850] [000001c8] libusb: debug [winusbx_submit_control_transfer] will use interface 0
[ 0.098852] [000001c8] libusb: debug [usbi_add_pollfd] add fd 2 events 1
[ 0.101851] [000024cc] libusb: debug [handle_events] poll() returned 1
[ 0.101851] [000024cc] libusb: debug [handle_events] caught a fish on the control pipe
[ 0.102847] [000024cc] libusb: debug [libusb_get_next_timeout] next timeout in 0.992300s
[ 0.102847] [000024cc] libusb: debug [libusb_handle_events_timeout_completed] doing our own event handling
[ 0.103849] [000024cc] libusb: debug [handle_events] poll fds modified, reallocating
[ 0.103849] [000024cc] libusb: debug [handle_events] poll() 3 fds with timeout in 993ms
[ 0.104848] [000024cc] libusb: debug [handle_events] poll() returned 1
[ 0.104848] [000024cc] libusb: debug [windows_handle_events] checking fd 2 with revents = 0001
[ 0.104848] [000024cc] libusb: debug [usbi_remove_pollfd] remove fd 2
[ 0.105847] [000024cc] libusb: debug [windows_transfer_callback] handling I/O completion with errcode 0, size 1
[ 0.105847] [000024cc] libusb: debug [libusb_release_interface] interface 0
[ 0.106847] [000024cc] libusb: debug [auto_release] auto-released interface 0
[ 0.106847] [000024cc] libusb: debug [usbi_handle_transfer_completion] transfer 000001C3C4F26B48 has callback 00007FFDB34C214E
[ 0.107846] [000024cc] libusb: debug [libusb_get_next_timeout] no URBs, no timeout!
[ 0.107846] [000024cc] libusb: debug [libusb_handle_events_timeout_completed] doing our own event handling
[ 0.108844] [000024cc] libusb: debug [handle_events] poll fds modified, reallocating
[ 0.108844] [000024cc] libusb: debug [handle_events] poll() 2 fds with timeout in 60000ms
{
  get: true,
  set: true,
  disabled: false,
  autoUpdate: false,
  async: false
}
```

In all the systems the buffer sent is `<Buffer a1 86 00 02 00 03 01 00 00>`

lsusb result:
```
Bus 001 Device 012: ID 2e7e:082d  Cute PC Pro
```

Udev rules in ubuntu:
```
SUBSYSTEM=="usb", ENV{DEVTYPE}=="usb_device", MODE="0666"
SUBSYSTEM=="usb", ATTRS{idVendor}=="2e7e", ATTRS{idProduct}=="082d", MODE="0666"
```

**Comment by dvil88** [comment]
@kevinmehall You are right... And it's strange because there isn't any app trying to access it (at least on my hand), I've even created a new VB machine, passthrough the webcam and got exactly the same errors, and It was a fresh Ubuntu.

Weird things :/ 

Thanks mate!
