### ISSUE TITLE
Error: LIBUSB_ERROR_ACCESS

### ISSUE THREAD

**Issue by qkren** [tessel/node-usb#432]
`E:\BACK\record-node-usb\node_modules\usb\usb.js:284
        this.device.__claimInterface(this.id)
                    ^

Error: LIBUSB_ERROR_ACCESS
    at Interface.claim (E:\BACK\record-node-usb\node_modules\usb\usb.js:284:14)
    at Object.<anonymous> (E:\BACK\record-node-usb\index.js:143:21)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)`

node 10.20.0 64  successed, but node 10.20.0 32  is error.

**Comment by thegecko** [comment]
This error is usually thrown if the device is in use (claimed) by another program/ process or the udev rules are incorrect when using Linux

**Comment by thegecko** [comment]
Closing due to no more comments
