### ISSUE TITLE
The specified procedure could not be found

### ISSUE THREAD

**Issue by nothingisdead** [tessel/node-usb#51]
I get the following error after installing the usb package and calling `require('usb')`. My environment is Windows XP 32 bit. I have installed the WinUSB driver and extracted the libusb package from [here](http://sourceforge.net/projects/libusb/files/libusb-1.0/libusb-1.0.18/) to C:\Program Files\libusb.

C:\Documents and Settings\test\My Documents\pos-addons\node_modules\usb\node_mod
ules\bindings-shyp\bindings.js:99
        throw e
              ^
Error: The specified procedure could not be found.
C:\Documents and Settings\test\My Documents\pos-addons\node_modules\usb\node_mod
ules\usb-shyp-win32-ia32\node-v11\usb_bindings.node
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at bindings (C:\Documents and Settings\test\My Documents\pos-addons\node_mod
ules\usb\node_modules\bindings-shyp\bindings.js:92:44)
    at Object.<anonymous> (C:\Documents and Settings\test\My Documents\pos-addon
s\node_modules\usb\usb.js:1:124)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)

**Comment by kevinmehall** [comment]
No idea. Re-open if anyone's reproduced this with a recent version.

**Comment by lishichao1002** [comment]
+1
```
module.js:482 Uncaught Error: The specified procedure could not be found.
\\?\Z:\Users\lishichao\workspaces\webstorm\soda-b-pc\dist\nw\node_modules\usb\src\binding\usb_bindings.node
```
